***

### Axes in Multi-dimensional Arrays
- 1D array has 1 axis (axis0).
- 2D array has 2 axes (axis0 = rows, axis1 = columns)
- 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 = columns in each layer)

In [4]:
import numpy as np

In [11]:
# Operations along Axes
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)
print("Sum of array: ",np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print("Sum of Columns: ", sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print("Sum of rows: ", sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3]) #row(0, 1, 2) & col(1, 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of array:  45
Sum of Columns:  [12 15 18]
Sum of rows:  [ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]
